server:
  port: 8084

spring:
  application:
    name: mail-service
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
#  mail:
#    default-encoding: UTF-8
#    host: smtp.daum.net
#    port: 465
#    username: limintae88@daum.net
#    password: awadevlim2021#
#    properties:
#      mail.smtp.host: smtp.daum.net
#      mail.smtp.port: 465
#      mail.smtp.auth: true
#      mail.smtp.ssl.enable: true
#      mail.debug: true
#    protocol: smtp

management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "info"
          - "refresh"
          - "beans"

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: false
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    health-check-url-path: http://${eureka.instance.hostname}:${server.port}/actuator/health
    status-page-url-path: http://${eureka.instance.hostname}:${server.port}/actuator/info
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8081/eureka/

kafka:
    bootstrapServers: 192.168.48.3:9092