server:
  port: 8082

spring:
  application:
    name: order-service
  profiles:
    active: local

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka/