server:
  port: 8082

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      - id: service-1
        uri: lb://SERVICE-1
        predicates:
          - Path=/order/**
        filters:
          - RewritePath=/order/?(?<segment>.*), /$\{segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka/