spring:
  h2:
    console:
      enabled: false
      path: /h2
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
    username: sa
    password:

#  sql:
#    init:
#      schema-locations: classpath*:db/hsqldb/schema.sql
#      data-locations: classpath*:db/hsqldb/data.sql
#      mode: always