spring:
  h2:
    console:
      enabled: false
      path: /h2
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
    username: sa
    password:

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: false
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    health-check-url-path: http://${eureka.instance.hostname}:${server.port}/actuator/health
    status-page-url-path: http://${eureka.instance.hostname}:${server.port}/actuator/info
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8081/eureka/

#  sql:
#    init:
#      schema-locations: classpath*:db/hsqldb/schema.sql
#      data-locations: classpath*:db/hsqldb/data.sql
#      mode: always